### ISSUE TITLE
vb 4.2.1 on mac osx 1.8.1 , `vagrant up` lead to system reboot

### ISSUE THREAD

**Issue by cooka** [xironix/freebsd-vagrant#1]
it seems the virtualbox guest additional tool's version is 4.1.22, may be the reason.
can you update the guest tool in the freebsd image? which the latest version is 4.2.4.

**Comment by xironix** [comment]
I havent tested on my MacBook, but I'll check it out. However, unfortunately the latest guest additions for FreeBSD is 4.1.22. If you download the guest additions from Oracle, it'll abort the install saying the detected system is not Solaris.

EDIT: Which image are you using? The UFS or the ZFS image?

**Comment by xironix** [comment]
I just tested both the ZFS and UFS FreeBSD vagrant boxes on my Mac OS X 10.8.1 system and had no issues. Unless you can provide further details into what is going on (console logs or such), I am going to have to close this issue.

Sorry I couldn't help.

**Comment by cooka** [comment]
now i see, it must be the matter that I ran Parallels and Virtualbox at the same time.

**Comment by xironix** [comment]
Glad you solved the problem.

In case you're interested, I'll be updating the Vagrant boxes to 9.1-RC3 today. I should have them up there in an hour or so.

**Comment by cooka** [comment]
thanks for your work, current version runs smoothly, 
and I'd be glad to download the final release later..  I am almost sure you'd update it to the final release a few days later..
