### ISSUE TITLE
fsck on unclean shutdown of ufs version renders unbootable box

### ISSUE THREAD

**Issue by tschundler** [xironix/freebsd-vagrant#2]
IMO it is worth adding

fsck_y_enable="YES"

to /etc/rc.conf, at least for ufs builds.

Multiple times already I've had to start it via virtualbox gui just to run fsck so it could boot.

**Comment by xironix** [comment]
Thank you. I will add that to the next build and close this issue when the new build is up.

**Comment by mindreframer** [comment]
Hey, FreeBSD 9.1 is out :)))) This issue could be closed ))

**Comment by xironix** [comment]
I'll release a new build this evening sometime.

Also seems GitHub [removed the downloads page](https://github.com/blog/1302-goodbye-uploads). I'll have to look into that as well I suppose.

**Comment by xironix** [comment]
Hah! Seems CVSup has been deprecated.

**Comment by xironix** [comment]
Commit cd740588cc7ec1d41762203e3e03c6ccf729639a both solves this issue and updates to FreeBSD 9.1-RELEASE.

Please note the Vagrant boxes are now hosted on Amazon S3. Please update your links accordingly.
