### ISSUE TITLE
Building Ports on these boxes

### ISSUE THREAD

**Issue by salgo** [xironix/freebsd-vagrant#3]
Hi, 

Can you give me some pointers of how to build ports on these boxes.

I'm missing something I'm suer but I'm struggling to get clang and the related C libraries onto the box to get the ports to build.  I've tried fetching stuff as packages using: 

```
PACKAGESITE=ftp://ftp.freebsd.org/pub/FreeBSD/ports/amd64/packages-9-current/Latest/ pkg_add -r clang
```

etc but lack the knowledge to know what packages I need to fetch to get my ports to build.

Thanks,

Andy

**Comment by salgo** [comment]
Here's what I'm seeing when I try to build MySQL Server for example 

root@vagrant-freebsd:/usr/local # portmaster databases/mysql55-server

===>>> Port directory: /usr/ports/databases/mysql55-server

===>>> Gathering distinfo list for installed ports

===>>> Launching 'make checksum' for databases/mysql55-server in background
===>>> Gathering dependency list for databases/mysql55-server from ports
===>>> Launching child to install databases/mysql55-client

===>>> databases/mysql55-server >> databases/mysql55-client (1/1)

===>>> Port directory: /usr/ports/databases/mysql55-client

===>>> Launching 'make checksum' for databases/mysql55-client in background
===>>> Gathering dependency list for databases/mysql55-client from ports
===>>> Initial dependency check complete for databases/mysql55-client

===>>> Continuing initial dependency check for databases/mysql55-server
===>>> Initial dependency check complete for databases/mysql55-server

===>>> databases/mysql55-server >> (1)

===>>> The following actions will be taken if you choose to proceed:
    Install databases/mysql55-server
    Install databases/mysql55-client

===>>> Proceed? y/n [y] y

===>>> Starting build for databases/mysql55-server <<<===

===>>> Starting check for build dependencies
===>>> Gathering dependency list for databases/mysql55-server from ports
===>>> Launching child to install databases/mysql55-client

===>>> databases/mysql55-server >> databases/mysql55-client (1/1)

===>>> Port directory: /usr/ports/databases/mysql55-client

===>>> Starting check for build dependencies
===>>> Gathering dependency list for databases/mysql55-client from ports
===>>> Dependency check complete for databases/mysql55-client

===>>> databases/mysql55-server >> databases/mysql55-client (1/1)

===>  Cleaning for mysql-client-5.5.29
===>  Found saved configuration for mysql-client-5.5.29
===>  Extracting for mysql-client-5.5.29
=> SHA256 Checksum OK for mysql-5.5.29.tar.gz.
===>  Patching for mysql-client-5.5.29
===>  Applying FreeBSD patches for mysql-client-5.5.29
===>   mysql-client-5.5.29 depends on file: /usr/local/bin/cmake - found
===>  Configuring for mysql-client-5.5.29
/bin/mkdir -p /usr/ports/databases/mysql55-client/work/mysql-5.5.29
-- Running cmake version 2.8.9
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- broken
CMake Error at /usr/local/share/cmake/Modules/CMakeTestCCompiler.cmake:52 (MESSAGE):
  The C compiler "/usr/bin/clang" is not able to compile a simple test
  program.

  It fails with the following output:

   Change Dir: /usr/ports/databases/mysql55-client/work/mysql-5.5.29/CMakeFiles/CMakeTmp

  Run Build Command:/usr/local/bin/gmake "cmTryCompileExec3324818467/fast"

  /usr/local/bin/gmake -f
  CMakeFiles/cmTryCompileExec3324818467.dir/build.make
  CMakeFiles/cmTryCompileExec3324818467.dir/build

  gmake[1]: Entering directory
  `/usr/ports/databases/mysql55-client/work/mysql-5.5.29/CMakeFiles/CMakeTmp'

  /usr/local/bin/cmake -E cmake_progress_report
  /usr/ports/databases/mysql55-client/work/mysql-5.5.29/CMakeFiles/CMakeTmp/CMakeFiles
  1

  Building C object
  CMakeFiles/cmTryCompileExec3324818467.dir/testCCompiler.c.o

  /usr/bin/clang -O2 -pipe -fno-strict-aliasing -march=native -o
  CMakeFiles/cmTryCompileExec3324818467.dir/testCCompiler.c.o -c
  /usr/ports/databases/mysql55-client/work/mysql-5.5.29/CMakeFiles/CMakeTmp/testCCompiler.c

  error: unknown target CPU 'i686'

  gmake[1]: **\* [CMakeFiles/cmTryCompileExec3324818467.dir/testCCompiler.c.o]
  Error 1

  gmake[1]: Leaving directory
  `/usr/ports/databases/mysql55-client/work/mysql-5.5.29/CMakeFiles/CMakeTmp'

  gmake: **\* [cmTryCompileExec3324818467/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:94 (PROJECT)

-- Configuring incomplete, errors occurred!
**\* [do-configure] Error code 1

Stop in /usr/ports/databases/mysql55-client.
**\* [build] Error code 1

Stop in /usr/ports/databases/mysql55-client.

===>>> make failed for databases/mysql55-client
===>>> Aborting update

===>>> Update for databases/mysql55-client failed
===>>> Aborting update

Terminated

===>>> You can restart from the point of failure with this command line:
       portmaster <flags> databases/mysql55-server databases/mysql55-client

**Comment by xironix** [comment]
I shall take a look at this now. Sorry it has taken me so long to get to this.

**Comment by salgo** [comment]
Thanks... No problem, I fixed it by swapping the building of ports back over to gcc but would rather use clang if possible.

**Comment by xironix** [comment]
I think the issue is how you're going about building this port. I managed to build it without issue.

When I package these boxes, I try to make them as small as possible. As such, I end up removing the /usr/ports and /usr/src directories. In order to build mysql with clang, simply do the following:

`portsnap fetch`
`portsnap extract`
`portmaster -BCD databases/mysql55-server`

This will fetch and extract a fresh /usr/ports tree and use portmaster (a nifty ports management tool) to install mysql. If you want to update the ports tree later, simply run `portsnap fetch` and `portsnap update`. The 'extract' process is only needed when we have no ports tree at all.

**Comment by xironix** [comment]
The README.md will be updated to make this more clear for people not that familiar with FreeBSD.

**Comment by salgo** [comment]
portsnap fetch
portsnap extract
portmaster -BCD databases/mysql55-server

Is exactly what I did!

**Comment by xironix** [comment]
That is very odd, perhaps the version of mysql at the time had a compile bug? When I ran the compile the other day I had no issue.
