### ISSUE TITLE
Can't convert StringIO into String

### ISSUE THREAD

**Issue by marc0der** [xironix/freebsd-vagrant#4]
I seem to be having an issue on startup of your UFS basebox when configuring the network. I see the following on the console at startup:

```
[default] Configuring and enabling network interfaces...
/home/marco/.rvm/gems/ruby-1.9.3-p385/gems/vagrant-1.0.6/lib/vagrant/communication/ssh.rb:82:in `initialize': can't convert StringIO into String (TypeError)
```

I am running VirtualBox 2.6 on Linux Mint (Ubuntu 12.10), and have the following Vagrant file.

```
Vagrant::Config.run do |config|
  config.vm.guest = :freebsd
  config.vm.box = 'freebsd91'
  config.vm.customize ['modifyvm', :id, '--nictype1', 'virtio']
  config.vm.network :hostonly, '192.168.33.10', :nic_type => 'virtio'
  config.vm.share_folder 'v-root', '/vagrant', '.', :nfs => true
end
```

It might be something silly on my side, but hope you can help!

**Comment by marc0der** [comment]
Thought I'd give a quick update, I have subsequently managed to fix this problem with a bit of a hack in the vagrant code. There seems to be a problem with the freebsd.rb file in the vagrant source code. Once the fix is applied, the freebsd box works perfectly.

For reference (and the solution), there is already an issue open on vagrant, and it can be found [here](https://github.com/mitchellh/vagrant/issues/1321).

**Comment by xironix** [comment]
Sorry I took so long to get back to you. I have also encountered the same issue and was able to solve it by downgrading to Vagrant 1.0.5. Thanks for posting the solution, I'll give it a try with 1.0.7 now.

On an amusing note (amusing insofar as that I didn't look at my own repo), I found this issue by searching for a solution to the problem.
