### ISSUE TITLE
Provide openjdk7 as preinstalled software package

### ISSUE THREAD

**Issue by marc0der** [xironix/freebsd-vagrant#5]
I've attempted installing openjdk7 on the box, but can't seem to get it working with portsnap. Would it be possible for you to provide this as default software in the future? This would be of great help to me!

**Comment by xironix** [comment]
I shall cancel the upload of my current boxes and take a look now. =D

Though do keep in mind, I do tend to compile with relatively minimal options to keep the Vagrant box size down.

**Comment by marc0der** [comment]
Thanks!

**Comment by xironix** [comment]
The latest Vagrant boxes now have openjdk7 included. Unfortunately this also increased their size by ~110MB each. It was nice being the smallest Vagrant boxes on [vagrantbox.es](http://vagrantbox.es). haha

**Comment by xironix** [comment]
Crap! I forgot to change `MAKE_JOBS_NUMBER` in `/etc/make.con`. If you are downloading the boxes now, do change that to something sane. I'll update the boxes again...

**Comment by marc0der** [comment]
Thanks for your effort, much appreciated.
On Mar 22, 2013 10:28 PM, "Steffen L. Norgren" notifications@github.com
wrote:

Crap! I forgot to change MAKE_JOBS_NUMBER in /etc/make.con. If you are
downloading the boxes now, do change that to something sane. I'll update
the boxes again...

—
Reply to this email directly or view it on
GitHubhttps://github.com/xironix/freebsd-vagrant/issues/5#issuecomment-15324622
.
